/**
 * API client for PlumeLens backend.
 *
 * Backend URL resolution:
 * - Electron runtime: via window.plumelens.getBackendUrl() (dynamic port)
 * - Fallback (dev shell / tests): http://127.0.0.1:8000
 *
 * All JSON requests carry `Content-Type: application/json` (FastAPI 0.132+ strict).
 * Electron runtime also carries a one-time bearer token generated by the main
 * process when it launches the local backend.
 */

/**
 * Resolve the backend URL on every request.
 *
 * 不缓存：Electron 启动早期 engine 还没 spawn 完，IPC 返回 null。每次重新拉
 * （IPC 异步开销 <1ms）。如果 engine 没 ready，无限轮询 200ms 间隔直到拿到 URL；
 * 不抛错 — 抛了之后 useEffect 一次性 hook（如 useAnalysisProgress 的 EventSource）
 * 拒绝重连，整个流死。
 */
async function getBackendUrl(): Promise<string> {
  if (typeof window !== 'undefined' && window.plumelens) {
    // 无限重试 200ms 间隔，每 5 秒打一次 console.warn 让用户知道进度
    let attempts = 0
    while (true) {
      const url = await window.plumelens.getBackendUrl()
      if (url) return url
      attempts += 1
      if (attempts % 25 === 0) {
        console.warn(`等待 engine 后端启动... ${(attempts * 200) / 1000}s`)
      }
      await new Promise((resolve) => setTimeout(resolve, 200))
    }
  }
  // Dev / test fallback (Playwright vite-server 模式 / 单元测试)
  return 'http://127.0.0.1:8000'
}

async function getBackendAuthToken(): Promise<string | null> {
  if (typeof window !== 'undefined' && window.plumelens) {
    return window.plumelens.getBackendAuthToken()
  }
  return null
}

export class ApiError extends Error {
  constructor(
    public readonly status: number,
    message: string,
    public readonly detail?: unknown,
  ) {
    super(message)
    this.name = 'ApiError'
  }
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const base = await getBackendUrl()
  const url = `${base}${path}`
  const headers = new Headers(init.headers)
  if (!headers.has('Content-Type') && init.body) {
    headers.set('Content-Type', 'application/json')
  }
  const token = await getBackendAuthToken()
  if (token && !headers.has('Authorization')) {
    headers.set('Authorization', `Bearer ${token}`)
  }
  const res = await fetch(url, { ...init, headers })
  if (!res.ok) {
    let detail: unknown
    try {
      detail = await res.json()
    } catch {
      detail = await res.text().catch(() => undefined)
    }
    const detailText = typeof detail === 'string' ? detail : JSON.stringify(detail)
    throw new ApiError(res.status, `${res.status} ${res.statusText}: ${detailText}`, detail)
  }
  if (res.status === 204) {
    return undefined as T
  }
  return (await res.json()) as T
}

// ---------------- Types (mirror engine/api/schemas/*) ----------------

export type LibraryStatus =
  | 'idle'
  | 'scanning'
  | 'hashing'
  | 'analyzing_partial'
  | 'ready'
  | 'updating'
  | 'path_missing'
  | 'exporting'
  | 'error'

export interface LibrarySummary {
  id: string
  display_name: string
  parent_path: string
  root_path: string
  status: LibraryStatus
  total_count: number
  analyzed_count: number
  recursive: boolean
  last_opened_at: string
  last_scanned_at: string | null
  last_analyzed_at: string | null
}

export interface BBox {
  x1: number
  y1: number
  x2: number
  y2: number
  confidence: number
}

export interface Keypoint {
  x: number
  y: number
  confidence: number
}

export interface PoseDetail {
  // 头部 5 关键点
  bill: Keypoint
  crown: Keypoint
  nape: Keypoint
  left_eye: Keypoint
  right_eye: Keypoint
  // 躯干 6 关键点(v2 新增,旧 cache 反序列化时有 default 占位)
  belly?: Keypoint
  breast?: Keypoint
  back?: Keypoint
  tail?: Keypoint
  left_wing?: Keypoint
  right_wing?: Keypoint
  // 5 项可见性
  head_visible: boolean
  eye_visible: boolean
  body_visible?: boolean
  tail_visible?: boolean
  wings_visible?: boolean
  // 3 项姿态(影响 grader 飞版升档)
  view_angle?: 'frontal' | 'side' | 'back' | 'unknown'
  facing?: 'left' | 'right' | 'unknown'
  posture?: 'perched' | 'flying' | 'unknown'
}

export interface SpeciesCandidate {
  canonical_sci?: string
  canonical_zh?: string
  canonical_en?: string
  confidence?: number
  recognition_state?: 'recognized' | 'uncertain' | 'unrecognized'
  reject_score?: number
  top1_top2_margin?: number
}

export interface AfOverlayPoint {
  index?: number
  x: number
  y: number
  width?: number
  height?: number
  bounds?: { x1: number; y1: number; x2: number; y2: number }
  in_focus?: boolean
  selected?: boolean
}

export interface AfOverlay {
  provider?: string
  mode?: number
  kind: 'point' | 'expanded' | 'zone' | 'whole_area' | 'unknown'
  source?: 'in_focus' | 'selected' | 'legacy'
  center: { x: number; y: number }
  bounds?: { x1: number; y1: number; x2: number; y2: number }
  points?: AfOverlayPoint[]
  focused_points?: AfOverlayPoint[]
  selected_points?: AfOverlayPoint[]
  focused_count?: number
  selected_count?: number
  point_count?: number
}

export interface BestDetection {
  index: number
  bbox: BBox
  pose: PoseDetail | null
  quality: { clipiqa: number; hyperiqa: number; combined: number } | null
  species: string | null
  species_latin: string | null
  manual_species: boolean
  // 每个 detection 独立的 species_source（多鸟图混合可见性的关键 — 后端 v6 schema）。
  // photo-level species_source 由 best detection 决定，但 detection-level 才是
  // 羽迹聚合 / confirm 按钮显隐的真实依据。
  species_source?:
    | 'none'
    | 'model'
    | 'model_unconfirmed'
    | 'manual'
    | 'group_consensus'
    | 'conflict'
  species_candidates: SpeciesCandidate[]
}

export interface BirdDetectionDetail extends BestDetection {
  is_best: boolean
}

export interface PhotoRow {
  id: string
  file_path: string
  file_name: string
  format: string | null
  width: number | null
  height: number | null
  thumb_grid: string | null
  thumb_preview: string | null
  // JPG/RAW 同名 pair 的 RAW 同伴文件信息(scanner v7+)。无 pair 时全 null。
  // UI 在卡片 / 复核屏显示 "+CR3 25 MB" 让用户知道还有原片可导出。
  companion_path?: string | null
  companion_format?: string | null
  companion_size?: number | null
  country?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  place?: string | null
  created_at: string
  shot_at: string // ISO8601 拍摄时间（EXIF DateTimeOriginal 优先）
  scene_id: number | null // 场景分组 id
  pipeline_version: string | null
  grade: string | null
  quality_score: number | null
  bird_count: number | null
  species: string | null
  species_latin: string | null
  manual_species: boolean
  species_source?:
    | 'none'
    | 'model'
    | 'model_unconfirmed'
    | 'manual'
    | 'group_consensus'
    | 'conflict'
  model_species?: string | null
  model_species_latin?: string | null
  group_species?: string | null
  group_species_latin?: string | null
  group_species_confidence?: number | null
  group_species_support?: number | null
  group_species_evidence?: number | null
  group_species_total?: number | null
  species_conflict?: boolean
  decision: string | null // manual grade override: select / usable / record / reject
  // 分析任务状态:done / failed / pending (前端按此显示"已分析" / "分析失败" / "等待分析")
  // failed 包含 task DEAD(attempts 用尽,通常是图损坏/读取失败)
  analysis_status?: 'done' | 'failed' | 'pending'
  // 失败原因的语义 code,前端用于 i18n 映射:broken_image / invalid_image / file_missing
  // / timeout / unknown。仅在 analysis_status=failed 时有意义。
  analysis_error_code?: string | null
  analysis_error?: string | null // 原始错误消息(英文 PIL/rawpy 输出),fallback 显示用
  exif: Record<string, unknown> | null // EXIF whitelist 字段 + structured AF metadata
  best_detection: BestDetection | null // 深度复核需要画 bbox / 关键点
  detections: BirdDetectionDetail[] | null
}

export interface LibraryDetail {
  library: LibrarySummary
  photos: PhotoRow[]
  photo_total?: number | null
  photo_offset?: number
  photo_limit?: number | null
  next_offset?: number | null
}

export interface PhotoThumbnailResponse {
  photo_id: string
  library_id: string
  built: boolean
  thumb_grid: string | null
  thumb_preview: string | null
}

export interface ImportLibraryRequest {
  root_path: string
  display_name?: string | null
  recursive?: boolean
}

export interface LibraryDetailOptions {
  limit?: number
  offset?: number
  signal?: AbortSignal
}

export interface UpdateLibraryRequest {
  display_name: string
}

export interface RelinkLibraryRequest {
  root_path: string
}

export interface RelinkLibraryResponse {
  library: LibrarySummary
  previous_root_path: string
  matched_photos: number
  relinked_photos: number
  missing_photos: number
  relinked_companions: number
}

export type TaskQueueStats = Record<string, number>

export interface QueueStatsResponse {
  library_id: string | null
  stats: TaskQueueStats
}

export interface AnalysisBatchResponse {
  library_id: string
  enqueued: number
  stats: TaskQueueStats
}

export interface AnalysisProgressEvent {
  library_id: string
  completed: number
  total: number
  pending: number
  processing: number
  failed: number
  dead: number
  current_photo_id: string | null
}

// Decisions
export type DecisionValue = 'select' | 'usable' | 'record' | 'reject' | null

export interface DecisionRow {
  photo_id: string
  decision: DecisionValue
}

export interface DecisionCountsResponse {
  library_id: string
  counts: Record<Exclude<DecisionValue, null>, number>
}

export interface ExportLibraryRequest {
  target_dir: string
  grades: Array<'select' | 'usable' | 'record' | 'reject'>
  min_score?: number | null
  max_score?: number | null
  copy_files?: boolean
  include_companions?: boolean
  include_xmp_sidecars?: boolean
  layout?: 'merged' | 'by_grade'
  preserve_structure?: boolean
  include_manifest?: boolean
}

export interface ExportLibraryResponse {
  library_id: string
  output_dir: string
  selected_count: number
  exported_count: number
  companion_count: number
  xmp_count: number
  skipped_missing: number
  failed_count: number
  manifest: {
    json: string | null
    csv: string | null
  }
}

export interface SpeciesOverrideValue {
  canonical_sci: string
  canonical_zh?: string | null
  canonical_en?: string | null
}

/** 写入 manual species 时同步上送的 detection bbox（原图像素坐标）— 后端用它做
    read-time IoU 匹配，让人工标注的归属随鸟稳定，不被 pipeline_version bump 时
    detections 数组重排错配。老 client 不传 → 后端 fallback 到 bird_index 匹配。 */
export interface SpeciesOverrideBBox {
  x1: number
  y1: number
  x2: number
  y2: number
}

export interface SpeciesOverrideRow {
  photo_id: string
  bird_index: number
  canonical_sci: string | null
  canonical_zh: string | null
  canonical_en: string | null
}

// ---------------- Endpoints ----------------

export const api = {
  // Libraries
  listLibraries: () => request<LibrarySummary[]>('/library'),
  importLibrary: (body: ImportLibraryRequest) =>
    request<LibrarySummary>('/library/import', {
      method: 'POST',
      body: JSON.stringify(body),
    }),
  libraryDetail: (id: string, options: LibraryDetailOptions = {}) => {
    const params = new URLSearchParams()
    if (options.limit !== undefined) params.set('limit', String(options.limit))
    if (options.offset !== undefined) params.set('offset', String(options.offset))
    const query = params.toString()
    return request<LibraryDetail>(`/library/${id}${query ? `?${query}` : ''}`, {
      signal: options.signal,
    })
  },
  updateLibrary: (id: string, body: UpdateLibraryRequest) =>
    request<LibrarySummary>(`/library/${id}`, {
      method: 'PATCH',
      body: JSON.stringify(body),
    }),
  relinkLibrary: (id: string, body: RelinkLibraryRequest) =>
    request<RelinkLibraryResponse>(`/library/${id}/relink`, {
      method: 'POST',
      body: JSON.stringify(body),
    }),
  deleteLibrary: (id: string) => request<void>(`/library/${id}`, { method: 'DELETE' }),
  buildThumbnails: (id: string) =>
    request<{ built: number; skipped: number; failed: number }>(`/library/${id}/thumbnails`, {
      method: 'POST',
    }),
  buildPhotoThumbnail: (photoId: string) =>
    request<PhotoThumbnailResponse>(`/library/photo/${photoId}/thumbnail`, { method: 'POST' }),
  libraryEventsUrl: async (libraryId: string): Promise<string> => {
    const base = await getBackendUrl()
    const token = await getBackendAuthToken()
    const url = new URL(`${base}/library/${libraryId}/events`)
    if (token) url.searchParams.set('token', token)
    return url.toString()
  },

  // Analysis
  startBatch: (libraryId: string, forceRerun = false) =>
    request<AnalysisBatchResponse>('/analysis/batch', {
      method: 'POST',
      body: JSON.stringify({ library_id: libraryId, force_rerun: forceRerun }),
    }),
  pauseAnalysis: (libraryId: string) =>
    request<QueueStatsResponse>(`/analysis/library/${libraryId}/pause`, { method: 'POST' }),
  resumeAnalysis: (libraryId: string) =>
    request<QueueStatsResponse>(`/analysis/library/${libraryId}/resume`, { method: 'POST' }),
  cancelAnalysis: (libraryId: string) =>
    request<QueueStatsResponse>(`/analysis/library/${libraryId}/cancel`, { method: 'POST' }),
  getQueueStats: (libraryId: string) =>
    request<QueueStatsResponse>(`/analysis/library/${libraryId}/stats`),

  // SSE — returns URL only; caller constructs EventSource
  progressUrl: async (libraryId: string): Promise<string> => {
    const base = await getBackendUrl()
    const token = await getBackendAuthToken()
    const url = new URL(`${base}/analysis/library/${libraryId}/progress`)
    if (token) url.searchParams.set('token', token)
    return url.toString()
  },

  // Decisions
  getDecision: (photoId: string) => request<DecisionRow>(`/decisions/photo/${photoId}`),
  setDecision: (photoId: string, decision: DecisionValue) =>
    request<DecisionRow>(`/decisions/photo/${photoId}`, {
      method: 'PUT',
      body: JSON.stringify({ decision }),
    }),
  batchSetDecisions: (updates: Array<[string, DecisionValue]>) =>
    request<{ updated: number }>('/decisions/batch', {
      method: 'POST',
      body: JSON.stringify({ updates }),
    }),
  setSpeciesOverride: (
    photoId: string,
    birdIndex: number,
    species: SpeciesOverrideValue | null,
    bbox?: SpeciesOverrideBBox | null,
  ) => {
    // bbox 在 set 和 clear 两种路径都送 — clear 时后端用它 IoU 反查 DB 实际行的
    // bird_index,避免 pipeline_version bump 后 caller 看到的下标 ≠ DB 下标导致删错行。
    const bboxBody = bbox ? { x1: bbox.x1, y1: bbox.y1, x2: bbox.x2, y2: bbox.y2 } : null
    return request<SpeciesOverrideRow>(`/decisions/photo/${photoId}/species/${birdIndex}`, {
      method: 'PUT',
      body: JSON.stringify(
        species
          ? {
              canonical_sci: species.canonical_sci,
              canonical_zh: species.canonical_zh ?? null,
              canonical_en: species.canonical_en ?? null,
              bbox: bboxBody,
            }
          : { canonical_sci: null, bbox: bboxBody },
      ),
    })
  },
  listLibraryDecisions: (libraryId: string) =>
    request<DecisionRow[]>(`/decisions/library/${libraryId}`),
  libraryDecisionCounts: (libraryId: string) =>
    request<DecisionCountsResponse>(`/decisions/library/${libraryId}/counts`),

  // Export
  exportLibrary: (libraryId: string, body: ExportLibraryRequest) =>
    request<ExportLibraryResponse>(`/export/library/${libraryId}`, {
      method: 'POST',
      body: JSON.stringify(body),
    }),

  // Reverse geocoding — provider chain(amap → baidu → tencent → nominatim → offline),
  // 后端按可用 key 自动选,前端只看 display_name + source 标识即可。
  reverseGeocode: (lat: number, lon: number, lang = 'zh-CN') =>
    request<ReverseGeocodeResponse>(
      `/geocoding/reverse?lat=${lat}&lon=${lon}&lang=${encodeURIComponent(lang)}`,
    ),

  // 羽迹三级地图聚合 — 后端 SQL 聚合,前端按需 lazy load 各级 GeoJSON
  geoSummary: () => request<GeoSummary>('/archive/geo/summary'),
  geoProvinces: () => request<GeoProvinceRow[]>('/archive/geo/provinces'),
  geoCities: (province: string) =>
    request<GeoCityRow[]>(`/archive/geo/cities?province=${encodeURIComponent(province)}`),
  geoSpots: (province: string, city: string) =>
    request<GeoSpot[]>(
      `/archive/geo/spots?province=${encodeURIComponent(province)}&city=${encodeURIComponent(city)}`,
    ),
}

export interface GeoSummary {
  total_with_gps: number
  resolved: number
  pending: number
  unresolved_count: number
  photos_without_gps: number
}

export interface GeoProvinceRow {
  province: string
  photo_count: number
  species_count: number
}

export interface GeoCityRow {
  city: string
  photo_count: number
  species_count: number
}

export interface GeoSpecies {
  name: string
  latin_name: string | null
  english_name: string | null
  photo_count: number
}

export interface GeoSpotPhoto {
  photo_id: string
  file_name: string
  species: GeoSpecies[]
  species_latin: string | null
  species_zh: string | null
  thumb_grid: string | null
  grade: string | null
  quality_score: number | null
}

export interface GeoSpot {
  lat: number
  lon: number
  place: string | null
  photo_count: number
  species_count: number
  species: GeoSpecies[]
  photos: GeoSpotPhoto[]
}

export interface ReverseGeocodeResponse {
  display_name: string | null
  source: 'amap' | 'baidu' | 'tencent' | 'nominatim' | 'offline' | null
  lat: number
  lon: number
}
